package nsop.neds.mycascais.Entities.Json;

import android.content.Context;

public class Labels {
    public String AboutApp;
    public String Agenda;
    public String Event;
    public String Events;
    public String DateSeparator;
    public String WeatherCascais;
    public String Date;
    public String Dates;
    public String Schedule;
    public String Purchase;
    public String Games;
    public String Videos;
    public String Photos;
    public String Informations;
    public String Suggestions;
    public String Place;
    public String Places;
    public String Price;
    public String Prices;
    public String Route;
    public String Routes;
    public String Category;
    public String Categories;
    public String IWantToSee;
    public String Parishes;
    public String AllParishes;
    public String AllCategories;
    public String Today;
    public String Settings;
    public String Calendar;
    public String Search;
    public String Welcome;
    public String English;
    public String Portuguese;
    public String Language;
    public String Back;
    public String Edit;
    public String NoSearchYet;
    public String NoResultsFound;
    public String Notifications;
    public String PasswordRecovery;
    public String ForgotPassword;
    public String PutEmail;
    public String Email;
    public String Send;
    public String OldPassword;
    public String NewPassword;
    public String Password;
    public String PasswordConfirmation;
    public String CreateAccount;
    public String PasswordRequirements;
    public String PasswordRequirementsMessage;
    public String PasswordMismatchMessage;
    public String AskForEmailText;
    public String LoginButton;
    public String EnterDetails;
    public String CreateAccountPrivacyPolicy;
    public String PasswordRecoverySMSSent;
    public String PasswordRecoveryInsertCode;
    public String PasswordRecoveryNewPassword;
    public String PasswordRecoveryNewPasswordRule;
    public String PasswordRuleLength;
    public String PasswordRuleUppercase;
    public String PasswordRuleLowercase;
    public String PasswordRuleNumber;
    public String PasswordRuleSpecial;
    public String TermsAndConditions;
    public String PrivacyPolicy;
    public String Change;
    public String Create;
    public String PersonalData;
    public String Documents;
    public String MobilePhone;
    public String LoginSubtitle;
    public String Hello;
    public String InvalidEmailAddress;
    public String InvalidEmail;
    public String InvalidContact;
    public String InvalidNIF;
    public String RequiredName;
    public String Birthdate;
    public String MyProfile;
    public String ChangePhoneNumberMessageMustBeDifferent;
    public String InvalidToken;
    public String Close;
    public String Description;
    public String Info;
    public String Free;
    public String Continue;
    public String ResendSMS;
    public String What;
    public String All;
    public String Yes;
    public String No;
    public String GetDirections;
    public String Map;
    public String InitTrip;
    public String SeeMap;
    public String OpenMap;
    public String Name;
    public String Address;
    public String Geolocation;
    public String Parish;
    public String Permissions;
    public String Location;
    public String AccountSettings;
    public String LogoutSuccess = "Terminou a sessão com sucesso.";
    public String ChangePasswordError = "Erro ao alterar palavra passe.";
    public String AlertMessage = "Alerta";
    public String ContactChanged = "Novo contacto atualizado com sucesso.";
    public String TryAgain;
    public String TermsAgree = "Para criar a conta necessita concordar com as condições.";
    public String Username;
    public String ProcessingData = "Processando dados...";
    public String UnsubscribedConfirmation;
    public String Confirm;
    public String Cancel;
    public String AppInMaintenanceMessage;
    public String DisclaimerTextInfo = "Autoriza a applicação %s aceder aos seguintes dados:";
    public String DisclaimerDeniedbyUser= "Autorização negada pelo utilizador.";
    public String AskForAuthentication;
    public String ContactAuth = "Contacto inserido com sucesso.";
    public String SubscriptionRemoved = "Subscrição removida com sucesso.";
    public String SubscriptionUpdated = "Subscrições atualizadas com sucesso.";
    public String AddingEmail = "Addicionando email...";
    public String AddingPhoneContact = "Addicionando telemóvel...";
    public String CheckYourInternetConnection = "Verifique a sua ligação à internet.";
    public String AuthenticationContact;
    public String Validated;
    public String NotValidated;
    public String SubscribedContents= "Conteúdos subscritos";;
    public String SubscribedNotifications = "Notificações subscritas";
    public String SubscribeNotifications = "Subscrever notificações";
    public String NonEventDates = "Não existem datas para este evento.";

    public String Consent = "Consentimentos";
    public String DisclaimerTitle;
}
